### ISSUE TITLE
如何取消个别选项。。

### ISSUE THREAD

**Issue by lly2016** [Exhen/douban-movie-helper#1]
就比如说pt站我只有几个站的账号，要那么多没必要，在代码里面直接注释掉也没用。。。

**Comment by Exhen** [comment]
右上角找【功能开关】-【站点开关】

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: lly2016 <notifications@github.com>
发送时间: Tuesday, June 19, 2018 2:52:12 PM
收件人: Exhen/douban-movie-helper
抄送: Subscribed
主题: [Exhen/douban-movie-helper] 如何取消个别选项。。 (#1)


就比如说pt站我只有几个站的账号，要那么多没必要，在代码里面直接注释掉也没用。。。

―
